pipeline:
  identifier: Build_jimsheldon_vagrant_1702486001880
  name: Build vagrant
  orgIdentifier: December_2023
  projectIdentifier: jim_sheldon_dec11
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Jim_GitHub
        repoName: vagrant
  stages:
    - stage:
        strategy:
          parallelism: 2
        name: test
        identifier: test
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Setup Ruby
                  identifier: setup_ruby
                  spec:
                    uses: ruby/setup-ruby@v1.152.0
                    with:
                      ruby-version: "3.2"
              - step:
                  type: Run
                  name: Dependencies
                  identifier: dependencies
                  spec:
                    shell: Sh
                    command: |-
                      apt-get update -y
                      apt -y install libarchive-tools
              - step:
                  type: RunTests
                  name: Run Tests
                  identifier: run_tests
                  spec:
                    language: Ruby
                    buildTool: Rspec
                    testGlobs: "**/test/unit/**/*_test.rb"
                    runOnlySelectedTests: true
                    enableTestSplitting: true
                    preCommand: bundle install
